FROM ubuntu:focal

ARG BOOST_VERSION=1.81.0
ARG BOOST_SHA256_HASH=71feeed900fbccca04a3b4f2f84a7c217186f28a940ed8b7ed4725986baf99fa

ENV DEBIAN_FRONTEND noninteractive

# Install package dependencies
RUN <<EOF
set -e
apt-get update && \
apt-get install -y --no-install-recommends \
    build-essential \
    software-properties-common \
    autoconf \
    automake \
    libtool \
    pkg-config \
    ca-certificates \
    libssl-dev \
    wget \
    git \
    sudo \
    curl \
    cmake \
    python3 \
    python3-pip \
    virtualenv \
    rapidjson-dev \
    libfuse2 \
    libssl-dev \
    libxcb-randr0-dev \
    libpulse-dev \
    libxkbcommon-x11-0 \
    build-essential \
    libgl1-mesa-dev \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-render-util0 \
    libsecret-1-dev
    libxcb-xinerama0

# Install AppImage packaging dependencies
apt-get -y install --no-install-recommends \
        libfontconfig \
        libxrender1 \
        file

apt-get clean
EOF

RUN <<EOF
set -e
cd /tmp
BOOST_VERSION_MOD=$(echo $BOOST_VERSION | tr . _)
wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_MOD}.tar.bz2
echo "$BOOST_SHA256_HASH boost_${BOOST_VERSION_MOD}.tar.bz2" | sha256sum --check --status
tar --bzip2 -xf boost_${BOOST_VERSION_MOD}.tar.bz2
cd boost_${BOOST_VERSION_MOD}
./bootstrap.sh --prefix=/usr/local
./b2 install
rm -rf /tmp/*
EOF

# Install Qt as we do in CI
# RUN <<EOF
# set -e
# pip3 install -U pip
# pip3 install aqtinstall
# aqt install-qt linux desktop 5.12.12
# mkdir -p /opt/qt512
# mv /5.12.12/gcc_64/* /opt/qt512
# EOF

RUN <<EOF
set -e
pip3 install -U pip
pip3 install aqtinstall
aqt install-qt linux desktop 5.15.2
mkdir -p /opt/qt515
mv /5.15.2/gcc_64/* /opt/qt515
EOF

ENV Qt5_DIR=/opt/qt515

ADD ./.patches /tmp/.patches

# Apply Qt patches
RUN patch "/opt/qt515/include/QtConcurrent/qtconcurrentthreadengine.h" /tmp/.patches/qt5-on-newer-gcc.patch

# vi: ft=dockerfile
