FROM ubuntu:focal

ARG BOOST_VERSION=1.81.0
ARG BOOST_SHA256_HASH=cc4b893acf645c9d4b698e9a0f08ca8846aa5d6c68275c14c3e7949c24109454

ENV DEBIAN_FRONTEND noninteractive

# Install package dependencies
RUN <<EOF
apt-get update && \
apt-get install -y --no-install-recommends \
    build-essential \
    software-properties-common \
    autoconf \
    automake \
    libtool \
    pkg-config \
    ca-certificates \
    libssl-dev \
    wget \
    curl && \
apt-get clean
EOF

RUN <<EOF
cd /tmp
BOOST_VERSION_MOD=$(echo $BOOST_VERSION | tr . _)
wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_MOD}.tar.bz2
echo "$BOOST_SHA256_HASH boost_${BOOST_VERSION_MOD}.tar.bz2" | sha256sum --check --status
tar --bzip2 -xf boost_${BOOST_VERSION_MOD}.tar.bz2
cd boost_${BOOST_VERSION_MOD}
./bootstrap.sh --prefix=/usr/local
./b2 install
rm -rf /tmp/*
EOF
